### ISSUE TITLE
Confusing/inaccurate description of "what's next" 

### ISSUE THREAD

**Issue by kjoewill** [learn-co-curriculum/transitioning-back-to-ruby#2]
The text of this new lesson says:

"Congratulations on completing the HTML and CSS introduction! **You have now completed all the Procedural Ruby lessons.**

The **upcoming Object Oriented Ruby section** will focus ..."

Yet, When I move on to the next lesson its all about Procedural Ruby.  Maybe a cut/paste error?

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thanks for your contribution 💙
